name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    # - name: Build
    #   uses: sersoft-gmbh/xcodebuild-action@v1.1
    #   with:
    #     workspace: DiscogsStreamer.xcworkspace
    #     scheme: DiscogsStreamer
    #     action: build
    - name: Test
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: DiscogsStreamer.xcodeproj
        scheme: DiscogsStreamer
        destination: platform=iOS Simulator,name=iPhone 11 Pro
        action: test
    - uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        # file: coverage.lcov
        fail_ci_if_error: true
    # - name: Start xcodebuild test
    #   run: xcodebuild clean test -project DiscogsStreamer.xcodeproj -scheme DiscogsStreamer -destination "platform=iOS Simulator,name=iPhone 11 Pro"
